import { DatabaseSync } from "node:sqlite";

export const LOCAL_PRODUCTION_LIKE_MIGRATION = `
  PRAGMA foreign_keys = ON;
  CREATE TABLE IF NOT EXISTS ingestion_schema_migrations (migration_id TEXT PRIMARY KEY);
  INSERT OR IGNORE INTO ingestion_schema_migrations VALUES ('001_ingestion_production');
  CREATE TABLE IF NOT EXISTS ingestion_organizations (organization_id TEXT PRIMARY KEY, payload_json TEXT NOT NULL CHECK (json_valid(payload_json)));
  CREATE TABLE IF NOT EXISTS ingestion_source_definitions (source_definition_id TEXT PRIMARY KEY, publisher_organization_id TEXT NOT NULL REFERENCES ingestion_organizations (organization_id), payload_json TEXT NOT NULL CHECK (json_valid(payload_json)));
  CREATE TABLE IF NOT EXISTS ingestion_recruitment_endpoints (recruitment_endpoint_id TEXT PRIMARY KEY, source_definition_id TEXT NOT NULL REFERENCES ingestion_source_definitions (source_definition_id), payload_json TEXT NOT NULL CHECK (json_valid(payload_json)), UNIQUE (recruitment_endpoint_id, source_definition_id));
  CREATE TABLE IF NOT EXISTS ingestion_authorization_audits (authorization_id TEXT PRIMARY KEY, collection_run_id TEXT NOT NULL UNIQUE, source_admission_id TEXT NOT NULL, recruitment_endpoint_id TEXT NOT NULL REFERENCES ingestion_recruitment_endpoints (recruitment_endpoint_id), endpoint TEXT NOT NULL, endpoint_purpose TEXT NOT NULL, reviewer TEXT NOT NULL, issued_at TEXT NOT NULL, evidence_id TEXT NOT NULL, payload_json TEXT NOT NULL CHECK (json_valid(payload_json)));
  CREATE TABLE IF NOT EXISTS ingestion_collection_runs (collection_run_id TEXT PRIMARY KEY, source_definition_id TEXT NOT NULL REFERENCES ingestion_source_definitions (source_definition_id), recruitment_endpoint_id TEXT NOT NULL REFERENCES ingestion_recruitment_endpoints (recruitment_endpoint_id), authorization_id TEXT NOT NULL REFERENCES ingestion_authorization_audits (authorization_id), status TEXT NOT NULL, started_at TEXT NOT NULL, completed_at TEXT NOT NULL, request_json TEXT NOT NULL CHECK (json_valid(request_json)), result_json TEXT NOT NULL CHECK (json_valid(result_json)), scheduler_dispatch_reference TEXT, UNIQUE (collection_run_id, recruitment_endpoint_id));
  CREATE TABLE IF NOT EXISTS ingestion_raw_blobs (raw_blob_id TEXT PRIMARY KEY, sha256 TEXT NOT NULL UNIQUE, mime_type TEXT NOT NULL, byte_length INTEGER NOT NULL CHECK (byte_length >= 0), object_path TEXT NOT NULL UNIQUE, original_url TEXT NOT NULL, created_at TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS ingestion_raw_blob_runs (raw_blob_id TEXT NOT NULL REFERENCES ingestion_raw_blobs (raw_blob_id), collection_run_id TEXT NOT NULL REFERENCES ingestion_collection_runs (collection_run_id), PRIMARY KEY (raw_blob_id, collection_run_id));
  CREATE TABLE IF NOT EXISTS ingestion_snapshots (snapshot_id TEXT PRIMARY KEY, collection_run_id TEXT NOT NULL REFERENCES ingestion_collection_runs (collection_run_id), recruitment_endpoint_id TEXT NOT NULL REFERENCES ingestion_recruitment_endpoints (recruitment_endpoint_id), raw_blob_id TEXT REFERENCES ingestion_raw_blobs (raw_blob_id), transport_status TEXT NOT NULL CHECK (transport_status IN ('SUCCESS', 'FAILED')), content_hash TEXT, content_length INTEGER, request_json TEXT NOT NULL CHECK (json_valid(request_json)), response_json TEXT NOT NULL CHECK (json_valid(response_json)), observed_at TEXT NOT NULL, payload_json TEXT NOT NULL CHECK (json_valid(payload_json)), CHECK ((transport_status = 'SUCCESS' AND raw_blob_id IS NOT NULL AND content_hash IS NOT NULL AND content_length IS NOT NULL) OR transport_status = 'FAILED'));
  CREATE TABLE IF NOT EXISTS ingestion_extracted_records (extracted_record_id TEXT PRIMARY KEY, snapshot_id TEXT NOT NULL REFERENCES ingestion_snapshots (snapshot_id), source_definition_id TEXT NOT NULL REFERENCES ingestion_source_definitions (source_definition_id), payload_json TEXT NOT NULL CHECK (json_valid(payload_json)));
  CREATE TABLE IF NOT EXISTS ingestion_source_occurrences (source_occurrence_id TEXT PRIMARY KEY, source_definition_id TEXT NOT NULL REFERENCES ingestion_source_definitions (source_definition_id), recruitment_endpoint_id TEXT NOT NULL REFERENCES ingestion_recruitment_endpoints (recruitment_endpoint_id), identity_hash TEXT NOT NULL UNIQUE, payload_json TEXT NOT NULL CHECK (json_valid(payload_json)));
  CREATE TABLE IF NOT EXISTS ingestion_source_occurrence_versions (source_occurrence_version_id TEXT PRIMARY KEY, source_occurrence_id TEXT NOT NULL REFERENCES ingestion_source_occurrences (source_occurrence_id), extracted_record_id TEXT NOT NULL REFERENCES ingestion_extracted_records (extracted_record_id), revision INTEGER NOT NULL CHECK (revision > 0), semantic_hash TEXT NOT NULL, payload_json TEXT NOT NULL CHECK (json_valid(payload_json)), UNIQUE (source_occurrence_id, revision), UNIQUE (source_occurrence_id, semantic_hash));
  CREATE TABLE IF NOT EXISTS ingestion_canonical_opportunities (canonical_opportunity_id TEXT PRIMARY KEY, identity_hash TEXT NOT NULL UNIQUE, payload_json TEXT NOT NULL CHECK (json_valid(payload_json)));
  CREATE TABLE IF NOT EXISTS ingestion_opportunity_versions (opportunity_version_id TEXT PRIMARY KEY, canonical_opportunity_id TEXT NOT NULL REFERENCES ingestion_canonical_opportunities (canonical_opportunity_id), revision INTEGER NOT NULL CHECK (revision > 0), semantic_hash TEXT NOT NULL, payload_json TEXT NOT NULL CHECK (json_valid(payload_json)), UNIQUE (canonical_opportunity_id, revision), UNIQUE (canonical_opportunity_id, semantic_hash));
  CREATE TABLE IF NOT EXISTS ingestion_opportunity_version_sources (opportunity_version_id TEXT NOT NULL REFERENCES ingestion_opportunity_versions (opportunity_version_id), source_occurrence_version_id TEXT NOT NULL REFERENCES ingestion_source_occurrence_versions (source_occurrence_version_id), source_ordinal INTEGER NOT NULL CHECK (source_ordinal >= 0), PRIMARY KEY (opportunity_version_id, source_occurrence_version_id));
  CREATE TABLE IF NOT EXISTS ingestion_requirement_facts (requirement_fact_id TEXT PRIMARY KEY, opportunity_version_id TEXT NOT NULL REFERENCES ingestion_opportunity_versions (opportunity_version_id), logic_group_id TEXT NOT NULL, payload_json TEXT NOT NULL CHECK (json_valid(payload_json)));
  CREATE TABLE IF NOT EXISTS ingestion_requirement_evidence (requirement_evidence_id TEXT PRIMARY KEY, requirement_fact_id TEXT NOT NULL REFERENCES ingestion_requirement_facts (requirement_fact_id), snapshot_id TEXT NOT NULL REFERENCES ingestion_snapshots (snapshot_id), payload_json TEXT NOT NULL CHECK (json_valid(payload_json)));
  CREATE TABLE IF NOT EXISTS ingestion_candidate_profiles (candidate_profile_id TEXT PRIMARY KEY, payload_json TEXT NOT NULL CHECK (json_valid(payload_json)));
  CREATE TABLE IF NOT EXISTS ingestion_eligibility_assessments (eligibility_assessment_id TEXT PRIMARY KEY, candidate_profile_id TEXT NOT NULL REFERENCES ingestion_candidate_profiles (candidate_profile_id), opportunity_version_id TEXT NOT NULL REFERENCES ingestion_opportunity_versions (opportunity_version_id), result TEXT NOT NULL, payload_json TEXT NOT NULL CHECK (json_valid(payload_json)));
  CREATE TABLE IF NOT EXISTS ingestion_eligibility_assessment_facts (eligibility_assessment_id TEXT NOT NULL REFERENCES ingestion_eligibility_assessments (eligibility_assessment_id), requirement_fact_id TEXT NOT NULL REFERENCES ingestion_requirement_facts (requirement_fact_id), fact_ordinal INTEGER NOT NULL CHECK (fact_ordinal >= 0), PRIMARY KEY (eligibility_assessment_id, requirement_fact_id));
  CREATE TABLE IF NOT EXISTS ingestion_eligibility_assessment_evidence (eligibility_assessment_id TEXT NOT NULL REFERENCES ingestion_eligibility_assessments (eligibility_assessment_id), requirement_evidence_id TEXT NOT NULL REFERENCES ingestion_requirement_evidence (requirement_evidence_id), evidence_ordinal INTEGER NOT NULL CHECK (evidence_ordinal >= 0), PRIMARY KEY (eligibility_assessment_id, requirement_evidence_id));
  CREATE TABLE IF NOT EXISTS ingestion_assessment_deferrals (opportunity_version_id TEXT PRIMARY KEY REFERENCES ingestion_opportunity_versions (opportunity_version_id), status TEXT NOT NULL CHECK (status = 'NOT_ASSESSED_INSUFFICIENT_REQUIREMENT_EVIDENCE'), reason TEXT NOT NULL);
  CREATE TRIGGER IF NOT EXISTS ingestion_raw_blobs_no_update BEFORE UPDATE ON ingestion_raw_blobs BEGIN SELECT RAISE(ABORT, 'ingestion_raw_blobs is append-only'); END;
  CREATE TRIGGER IF NOT EXISTS ingestion_raw_blobs_no_delete BEFORE DELETE ON ingestion_raw_blobs BEGIN SELECT RAISE(ABORT, 'ingestion_raw_blobs is append-only'); END;
  CREATE TRIGGER IF NOT EXISTS ingestion_snapshots_no_update BEFORE UPDATE ON ingestion_snapshots BEGIN SELECT RAISE(ABORT, 'ingestion_snapshots is append-only'); END;
  CREATE TRIGGER IF NOT EXISTS ingestion_snapshots_no_delete BEFORE DELETE ON ingestion_snapshots BEGIN SELECT RAISE(ABORT, 'ingestion_snapshots is append-only'); END;
  CREATE TRIGGER IF NOT EXISTS ingestion_extracted_records_no_update BEFORE UPDATE ON ingestion_extracted_records BEGIN SELECT RAISE(ABORT, 'ingestion_extracted_records is append-only'); END;
  CREATE TRIGGER IF NOT EXISTS ingestion_extracted_records_no_delete BEFORE DELETE ON ingestion_extracted_records BEGIN SELECT RAISE(ABORT, 'ingestion_extracted_records is append-only'); END;
  CREATE TRIGGER IF NOT EXISTS ingestion_source_occurrence_versions_no_update BEFORE UPDATE ON ingestion_source_occurrence_versions BEGIN SELECT RAISE(ABORT, 'ingestion_source_occurrence_versions is append-only'); END;
  CREATE TRIGGER IF NOT EXISTS ingestion_source_occurrence_versions_no_delete BEFORE DELETE ON ingestion_source_occurrence_versions BEGIN SELECT RAISE(ABORT, 'ingestion_source_occurrence_versions is append-only'); END;
  CREATE TRIGGER IF NOT EXISTS ingestion_opportunity_versions_no_update BEFORE UPDATE ON ingestion_opportunity_versions BEGIN SELECT RAISE(ABORT, 'ingestion_opportunity_versions is append-only'); END;
  CREATE TRIGGER IF NOT EXISTS ingestion_opportunity_versions_no_delete BEFORE DELETE ON ingestion_opportunity_versions BEGIN SELECT RAISE(ABORT, 'ingestion_opportunity_versions is append-only'); END;
  CREATE TRIGGER IF NOT EXISTS ingestion_requirement_facts_no_update BEFORE UPDATE ON ingestion_requirement_facts BEGIN SELECT RAISE(ABORT, 'ingestion_requirement_facts is append-only'); END;
  CREATE TRIGGER IF NOT EXISTS ingestion_requirement_facts_no_delete BEFORE DELETE ON ingestion_requirement_facts BEGIN SELECT RAISE(ABORT, 'ingestion_requirement_facts is append-only'); END;
  CREATE TRIGGER IF NOT EXISTS ingestion_requirement_evidence_no_update BEFORE UPDATE ON ingestion_requirement_evidence BEGIN SELECT RAISE(ABORT, 'ingestion_requirement_evidence is append-only'); END;
  CREATE TRIGGER IF NOT EXISTS ingestion_requirement_evidence_no_delete BEFORE DELETE ON ingestion_requirement_evidence BEGIN SELECT RAISE(ABORT, 'ingestion_requirement_evidence is append-only'); END;
  CREATE TRIGGER IF NOT EXISTS ingestion_eligibility_assessments_no_update BEFORE UPDATE ON ingestion_eligibility_assessments BEGIN SELECT RAISE(ABORT, 'ingestion_eligibility_assessments is append-only'); END;
  CREATE TRIGGER IF NOT EXISTS ingestion_eligibility_assessments_no_delete BEFORE DELETE ON ingestion_eligibility_assessments BEGIN SELECT RAISE(ABORT, 'ingestion_eligibility_assessments is append-only'); END;
`;

export function createProductionLikeDatabase() {
  const database = new DatabaseSync(":memory:");
  database.exec(LOCAL_PRODUCTION_LIKE_MIGRATION);
  return database;
}
