-- P2-06 production ingestion contract. Deployment requires separate human authorization.
-- This migration creates only the isolated ingestion_production schema.
BEGIN;
CREATE SCHEMA IF NOT EXISTS ingestion_production;

CREATE TABLE IF NOT EXISTS ingestion_production.schema_migrations (migration_id TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO ingestion_production.schema_migrations (migration_id) VALUES ('001_ingestion_production') ON CONFLICT (migration_id) DO NOTHING;
CREATE TABLE IF NOT EXISTS ingestion_production.organizations (organization_id TEXT PRIMARY KEY, payload_json JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS ingestion_production.source_definitions (source_definition_id TEXT PRIMARY KEY, publisher_organization_id TEXT NOT NULL REFERENCES ingestion_production.organizations (organization_id), payload_json JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS ingestion_production.recruitment_endpoints (recruitment_endpoint_id TEXT PRIMARY KEY, source_definition_id TEXT NOT NULL REFERENCES ingestion_production.source_definitions (source_definition_id), payload_json JSONB NOT NULL, UNIQUE (recruitment_endpoint_id, source_definition_id));
CREATE TABLE IF NOT EXISTS ingestion_production.authorization_audits (authorization_id TEXT PRIMARY KEY, collection_run_id TEXT NOT NULL UNIQUE, source_admission_id TEXT NOT NULL, recruitment_endpoint_id TEXT NOT NULL REFERENCES ingestion_production.recruitment_endpoints (recruitment_endpoint_id), endpoint TEXT NOT NULL, endpoint_purpose TEXT NOT NULL, reviewer TEXT NOT NULL, issued_at TIMESTAMPTZ NOT NULL, evidence_id TEXT NOT NULL, payload_json JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS ingestion_production.collection_runs (collection_run_id TEXT PRIMARY KEY, source_definition_id TEXT NOT NULL REFERENCES ingestion_production.source_definitions (source_definition_id), recruitment_endpoint_id TEXT NOT NULL REFERENCES ingestion_production.recruitment_endpoints (recruitment_endpoint_id), authorization_id TEXT NOT NULL REFERENCES ingestion_production.authorization_audits (authorization_id), status TEXT NOT NULL CHECK (status IN ('SUCCESS', 'FAILED', 'PARTIAL', 'SUSPICIOUS_EMPTY')), started_at TIMESTAMPTZ NOT NULL, completed_at TIMESTAMPTZ NOT NULL, request_metadata JSONB NOT NULL, result_metadata JSONB NOT NULL, scheduler_dispatch_reference TEXT, UNIQUE (collection_run_id, recruitment_endpoint_id));
CREATE TABLE IF NOT EXISTS ingestion_production.raw_blobs (raw_blob_id TEXT PRIMARY KEY, sha256 CHAR(64) NOT NULL UNIQUE CHECK (sha256 ~ '^[0-9a-f]{64}$'), mime_type TEXT NOT NULL, byte_length BIGINT NOT NULL CHECK (byte_length >= 0), object_path TEXT NOT NULL UNIQUE, original_url TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS ingestion_production.raw_blob_runs (raw_blob_id TEXT NOT NULL REFERENCES ingestion_production.raw_blobs (raw_blob_id), collection_run_id TEXT NOT NULL REFERENCES ingestion_production.collection_runs (collection_run_id), PRIMARY KEY (raw_blob_id, collection_run_id));
CREATE TABLE IF NOT EXISTS ingestion_production.snapshots (snapshot_id TEXT PRIMARY KEY, collection_run_id TEXT NOT NULL REFERENCES ingestion_production.collection_runs (collection_run_id), recruitment_endpoint_id TEXT NOT NULL REFERENCES ingestion_production.recruitment_endpoints (recruitment_endpoint_id), raw_blob_id TEXT REFERENCES ingestion_production.raw_blobs (raw_blob_id), transport_status TEXT NOT NULL CHECK (transport_status IN ('SUCCESS', 'FAILED')), content_hash CHAR(64), content_length BIGINT, request_metadata JSONB NOT NULL, response_metadata JSONB NOT NULL, observed_at TIMESTAMPTZ NOT NULL, payload_json JSONB NOT NULL, CHECK ((transport_status = 'SUCCESS' AND raw_blob_id IS NOT NULL AND content_hash IS NOT NULL AND content_length IS NOT NULL) OR transport_status = 'FAILED'));
CREATE TABLE IF NOT EXISTS ingestion_production.extracted_records (extracted_record_id TEXT PRIMARY KEY, snapshot_id TEXT NOT NULL REFERENCES ingestion_production.snapshots (snapshot_id), source_definition_id TEXT NOT NULL REFERENCES ingestion_production.source_definitions (source_definition_id), payload_json JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS ingestion_production.source_occurrences (source_occurrence_id TEXT PRIMARY KEY, source_definition_id TEXT NOT NULL REFERENCES ingestion_production.source_definitions (source_definition_id), recruitment_endpoint_id TEXT NOT NULL REFERENCES ingestion_production.recruitment_endpoints (recruitment_endpoint_id), identity_hash TEXT NOT NULL UNIQUE, payload_json JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS ingestion_production.source_occurrence_versions (source_occurrence_version_id TEXT PRIMARY KEY, source_occurrence_id TEXT NOT NULL REFERENCES ingestion_production.source_occurrences (source_occurrence_id), extracted_record_id TEXT NOT NULL REFERENCES ingestion_production.extracted_records (extracted_record_id), revision INTEGER NOT NULL CHECK (revision > 0), semantic_hash TEXT NOT NULL, payload_json JSONB NOT NULL, UNIQUE (source_occurrence_id, revision), UNIQUE (source_occurrence_id, semantic_hash));
CREATE TABLE IF NOT EXISTS ingestion_production.canonical_opportunities (canonical_opportunity_id TEXT PRIMARY KEY, identity_hash TEXT NOT NULL UNIQUE, payload_json JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS ingestion_production.opportunity_versions (opportunity_version_id TEXT PRIMARY KEY, canonical_opportunity_id TEXT NOT NULL REFERENCES ingestion_production.canonical_opportunities (canonical_opportunity_id), revision INTEGER NOT NULL CHECK (revision > 0), semantic_hash TEXT NOT NULL, payload_json JSONB NOT NULL, UNIQUE (canonical_opportunity_id, revision), UNIQUE (canonical_opportunity_id, semantic_hash));
CREATE TABLE IF NOT EXISTS ingestion_production.opportunity_version_sources (opportunity_version_id TEXT NOT NULL REFERENCES ingestion_production.opportunity_versions (opportunity_version_id), source_occurrence_version_id TEXT NOT NULL REFERENCES ingestion_production.source_occurrence_versions (source_occurrence_version_id), source_ordinal INTEGER NOT NULL CHECK (source_ordinal >= 0), PRIMARY KEY (opportunity_version_id, source_occurrence_version_id), UNIQUE (opportunity_version_id, source_ordinal));
CREATE TABLE IF NOT EXISTS ingestion_production.requirement_facts (requirement_fact_id TEXT PRIMARY KEY, opportunity_version_id TEXT NOT NULL REFERENCES ingestion_production.opportunity_versions (opportunity_version_id), logic_group_id TEXT NOT NULL, payload_json JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS ingestion_production.requirement_evidence (requirement_evidence_id TEXT PRIMARY KEY, requirement_fact_id TEXT NOT NULL REFERENCES ingestion_production.requirement_facts (requirement_fact_id), snapshot_id TEXT NOT NULL REFERENCES ingestion_production.snapshots (snapshot_id), payload_json JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS ingestion_production.candidate_profiles (candidate_profile_id TEXT PRIMARY KEY, payload_json JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS ingestion_production.eligibility_assessments (eligibility_assessment_id TEXT PRIMARY KEY, candidate_profile_id TEXT NOT NULL REFERENCES ingestion_production.candidate_profiles (candidate_profile_id), opportunity_version_id TEXT NOT NULL REFERENCES ingestion_production.opportunity_versions (opportunity_version_id), result TEXT NOT NULL CHECK (result IN ('ELIGIBLE', 'LIKELY_ELIGIBLE', 'NEEDS_REVIEW', 'LIKELY_INELIGIBLE', 'INELIGIBLE')), payload_json JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS ingestion_production.eligibility_assessment_facts (eligibility_assessment_id TEXT NOT NULL REFERENCES ingestion_production.eligibility_assessments (eligibility_assessment_id), requirement_fact_id TEXT NOT NULL REFERENCES ingestion_production.requirement_facts (requirement_fact_id), fact_ordinal INTEGER NOT NULL CHECK (fact_ordinal >= 0), PRIMARY KEY (eligibility_assessment_id, requirement_fact_id));
CREATE TABLE IF NOT EXISTS ingestion_production.eligibility_assessment_evidence (eligibility_assessment_id TEXT NOT NULL REFERENCES ingestion_production.eligibility_assessments (eligibility_assessment_id), requirement_evidence_id TEXT NOT NULL REFERENCES ingestion_production.requirement_evidence (requirement_evidence_id), evidence_ordinal INTEGER NOT NULL CHECK (evidence_ordinal >= 0), PRIMARY KEY (eligibility_assessment_id, requirement_evidence_id));
CREATE TABLE IF NOT EXISTS ingestion_production.assessment_deferrals (opportunity_version_id TEXT PRIMARY KEY REFERENCES ingestion_production.opportunity_versions (opportunity_version_id), status TEXT NOT NULL CHECK (status = 'NOT_ASSESSED_INSUFFICIENT_REQUIREMENT_EVIDENCE'), reason TEXT NOT NULL);

CREATE OR REPLACE FUNCTION ingestion_production.reject_mutation() RETURNS TRIGGER LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION '% is append-only', TG_TABLE_NAME; END; $$;
CREATE OR REPLACE FUNCTION ingestion_production.enable_append_only(target_table REGCLASS) RETURNS VOID LANGUAGE plpgsql AS $$ BEGIN EXECUTE format('CREATE TRIGGER ingestion_append_only BEFORE UPDATE OR DELETE ON %s FOR EACH ROW EXECUTE FUNCTION ingestion_production.reject_mutation()', target_table); END; $$;
SELECT ingestion_production.enable_append_only(table_name::REGCLASS) FROM (VALUES
  ('ingestion_production.raw_blobs'), ('ingestion_production.snapshots'), ('ingestion_production.extracted_records'), ('ingestion_production.source_occurrence_versions'), ('ingestion_production.opportunity_versions'), ('ingestion_production.requirement_facts'), ('ingestion_production.requirement_evidence'), ('ingestion_production.eligibility_assessments')
) AS append_only_tables(table_name);

REVOKE ALL ON SCHEMA ingestion_production FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA ingestion_production FROM PUBLIC;
COMMIT;
