import type { Job } from "@/lib/types";

// Supabase 尚未连接时展示的首批已核验 2027 届岗位。
// 每条记录均来自 2026-08-31 前可访问的招聘单位官网或已标注的高校就业网。
export const demoJobs: Job[] = [
  {
    id: "seed-kylin-legal-2027",
    job_id: "2027-麒麟软件-法务专员-001",
    announcement_url: "https://www.kylinos.cn/about/job/campusRecruitment/index.html",
    application_url: "https://kylinos.zhiye.com/campus/detail?jobAdId=75f86da3-4d16-4c91-b6ab-5648be60b189",
    unit_name: "麒麟软件有限公司",
    unit_type: "央企",
    system_name: "中国电子信息产业集团核心二级单位",
    industry: "基础软件",
    location: "北京",
    title: "2027校招—法务专员",
    direction: "法务",
    recruitment_year: 2027,
    batch: "秋季校园招聘",
    education: "硕士研究生及以上",
    non_law_rule: "可能接受",
    match_score: 4,
    salary: "未公开",
    development: "法务与合规",
    start_date: "2026-08-25",
    deadline: null,
    recruitment_status: "网申进行中",
    source_status: "官方来源",
    source_name: "麒麟软件校园招聘官网",
    source_updated_at: "2026-08-25T00:00:00+08:00",
    updated_at: "2026-08-31T00:00:00+08:00"
  },
  {
    id: "seed-oppo-legal-2027",
    job_id: "2027-OPPO-法务经理-001",
    announcement_url: "https://careers.oppo.com/university/oppo/campus/post/1765?recruitType=Graduate",
    application_url: "https://careers.oppo.com/university/oppo/campus/post/1765?recruitType=Graduate",
    unit_name: "OPPO",
    unit_type: "大型科技企业",
    system_name: "民营大型科技企业",
    industry: "消费电子与科技",
    location: "东莞",
    title: "2027届应届生校园招聘—法务经理",
    direction: "法务",
    recruitment_year: 2027,
    batch: "秋季校园招聘",
    education: "硕士研究生及以上",
    non_law_rule: "可能接受",
    match_score: 4,
    salary: "未公开",
    development: "涉外法务与商业合规",
    start_date: "2026-07-15",
    deadline: null,
    recruitment_status: "网申进行中",
    source_status: "官方来源",
    source_name: "OPPO招聘官网",
    source_updated_at: "2026-07-15T00:00:00+08:00",
    updated_at: "2026-08-31T00:00:00+08:00"
  },
  {
    id: "seed-taikang-compliance-2027",
    job_id: "2027-泰康基金-合规管理-001",
    announcement_url: "https://www.tkfunds.com.cn/aboutus/job/index.html",
    application_url: "https://www.tkfunds.com.cn/aboutus/job/index.html",
    unit_name: "泰康基金管理有限公司",
    unit_type: "金融机构",
    system_name: "金融体系",
    industry: "公募基金",
    location: "北京",
    title: "2027届校园招聘—合规管理",
    direction: "合规管理",
    recruitment_year: 2027,
    batch: "秋季校园招聘",
    education: "硕士研究生及以上",
    non_law_rule: "可能接受",
    match_score: 4,
    salary: "未公开",
    development: "法律合规、监察稽核与投资监督",
    start_date: "2026-03-25",
    deadline: null,
    recruitment_status: "网申进行中",
    source_status: "官方来源",
    source_name: "泰康基金官方网站",
    source_updated_at: "2026-08-28T00:00:00+08:00",
    updated_at: "2026-08-31T00:00:00+08:00"
  },
  {
    id: "seed-chinatelecom-support-2027",
    job_id: "2027-中国电信-综合支撑法律方向-001",
    announcement_url: "https://wejob.chinatelecom.com.cn/wt/TELE/web/index",
    application_url: "https://wejob.chinatelecom.com.cn/wt/TELE/web/index",
    unit_name: "中国电信集团有限公司及所属单位",
    unit_type: "央企",
    system_name: "国务院国资委央企",
    industry: "通信",
    location: "全国",
    title: "2027校园招聘—综合支撑（法律方向）",
    direction: "法律事务",
    recruitment_year: 2027,
    batch: "秋季校园招聘",
    education: "本科、硕士及博士",
    non_law_rule: "专业限制待核验",
    match_score: 3,
    salary: "未公开",
    development: "法律、财务审计与综合支撑",
    start_date: null,
    deadline: null,
    recruitment_status: "岗位陆续更新",
    source_status: "官方来源",
    source_name: "中国电信招聘官网",
    source_updated_at: "2026-08-31T00:00:00+08:00",
    updated_at: "2026-08-31T00:00:00+08:00"
  },
  {
    id: "seed-tcl-compliance-2027",
    job_id: "2027-TCL-合规法务部职位池-001",
    announcement_url: "https://zhaopin.tcl.com/campus/recruiting.html?id=59&jobmx=308501",
    application_url: "https://tcl.hotjob.cn/wt/TCL/web/index/campus",
    unit_name: "TCL科技集团",
    unit_type: "大型科技企业",
    system_name: "大型科技企业",
    industry: "智能科技与制造",
    location: "中国大陆及海外",
    title: "2027届全球校园招聘—合规法务部职位池",
    direction: "合规管理",
    recruitment_year: 2027,
    batch: "全球校园招聘",
    education: "学历要求待核验",
    non_law_rule: "专业限制待核验",
    match_score: 3,
    salary: "未公开",
    development: "合规法务",
    start_date: null,
    deadline: null,
    recruitment_status: "网申进行中",
    source_status: "官方来源",
    source_name: "TCL校园招聘官网",
    source_updated_at: "2026-08-31T00:00:00+08:00",
    updated_at: "2026-08-31T00:00:00+08:00"
  },
  {
    id: "seed-zhenghan-2027",
    job_id: "2027-虹桥正瀚-校园招聘-001",
    announcement_url: "https://www.zhenghan.com/news/2782.html",
    application_url: "https://www.zhenghan.com/news/2782.html",
    unit_name: "上海虹桥正瀚律师事务所",
    unit_type: "律所",
    system_name: "精品律所",
    industry: "法律服务",
    location: "上海",
    title: "2027届校园招聘—争议解决方向",
    direction: "法律事务",
    recruitment_year: 2027,
    batch: "校园招聘",
    education: "法学本科或研究生",
    non_law_rule: "专业限制待核验",
    match_score: 3,
    salary: "未公开",
    development: "复杂争议解决",
    start_date: "2026-05-13",
    deadline: null,
    recruitment_status: "招聘已启动",
    source_status: "官方来源",
    source_name: "虹桥正瀚律师事务所官网",
    source_updated_at: "2026-05-13T00:00:00+08:00",
    updated_at: "2026-08-31T00:00:00+08:00"
  },
  {
    id: "seed-ebscn-compliance-2027",
    job_id: "2027-光大证券-总部合规风控类-001",
    announcement_url: "https://career.nankai.edu.cn/correcruit/content/id/116621.html",
    application_url: null,
    unit_name: "光大证券股份有限公司",
    unit_type: "金融机构",
    system_name: "中国光大集团核心金融平台",
    industry: "证券",
    location: "上海",
    title: "2027校园招聘—总部合规风控类",
    direction: "合规管理",
    recruitment_year: 2027,
    batch: "秋季校园招聘",
    education: "硕士研究生及以上",
    non_law_rule: "可能接受",
    match_score: 4,
    salary: "15,000–20,000元/月（高校就业网信息）",
    development: "风险管理、法律合规、内部审计",
    start_date: "2026-08-20",
    deadline: null,
    recruitment_status: "网申进行中",
    source_status: "来源待核验",
    source_name: "南开大学就业信息网",
    source_updated_at: "2026-08-20T00:00:00+08:00",
    updated_at: "2026-08-31T00:00:00+08:00"
  }
];
